create table todos (
  id int generated by default as identity primary key not null,
  task text not null,
  is_complete boolean default false
);

create type priority as enum ('do_now', 'do_later', 'delegate', 'dont_do');

create table eisenhower (
  task_id int references todos on delete cascade not null primary key,
  priority priority not null default 'do_now',
  order_id int not null
)
