alter table "public"."todos" add column "index" int not null generated by default as identity;
alter table "public"."todos" add column "scheduled_date" date;

create function increment (starting_index int, list_date date, move_index int)
returns void as
$$
    begin
        update todos
        set index = index + 1
        where index >= starting_index AND index < move_index AND scheduled_date = list_date;
    end;
$$ language plpgsql;

create or replace function decrement_below(inclusive bool, starting int, list_date date) returns void as $$ begin
    update todos
    set index = index - 1
    where (index > starting OR (inclusive AND index = starting)) and scheduled_date = list_date;
end; $$ language plpgsql;

create or replace function increment_below(inclusive bool, starting int, list_date date) returns void as $$ begin
    update todos
    set index = index + 1
    where (index > starting OR (inclusive AND index = starting)) and scheduled_date = list_date;
end; $$ language plpgsql;

create function decrement (starting_index int, list_date date, move_index int)
    returns void as
$$
begin
    update todos
    set index = index - 1
    where index <= starting_index AND index > move_index AND scheduled_date = list_date;
end;
$$ language plpgsql volatile;

create function max_index (the_date date) returns int as
$$
select max(index) from todos where scheduled_date = the_date;
$$ language sql volatile;

